### ISSUE TITLE
user คนที่3

### ISSUE THREAD

**Issue by Bhirapat** [plaslide/INT100-G1-02--Love-3-sad#6]
3

 เจ้าของร้านน้ำปั่น
 
 อายุ 30 ปี
 
 อาชีพ เจ้าของร้านน้ำปั่น

 say  
 
 • อยากให้ร้านขายดี เป็นที่นิยม
 
 do  
 
 • เฝ้าร้าน
 
 • ขายน้ำปั่น
 
 • ขายขนม
 
 think 
 
• งานไม่มีปัญหา

 feel

 • รู้สึกสนุกกับการทำงาน
 
 • ไม่เครียด พราะป็นสิ่งที่ตนเองชอบ
 
 Journey map 
 
![img3](https://github.com/Bhirapat/img/blob/main/Screenshot%202024-09-25%20175802.png) 

To Do

• เปิดร้าน เฝ้าร้าน ขายน้ำปั่น ขายขนม

What

• ตื่นเวลา 3:00 น. มาจัดร้านเวลา 3:30 น. ขายของถึง 18:30 น.

How

• เดินทางจากบ้านมาถึงที่ทำงานระยะเวลา 30 นาที

Why

• ทำงานหารายได้เลี้ยงชีพไว้ซื้อของเพิ่มความสุขให้ตนเอง

POV (point of view)

1. We met

 • เจ้าของร้านน้ำปั่น

2. We were surprised to notice :

 • ทำงาน 6 วัน หยุดแค่วันอาทิตย์ ถึงจะลาก็มีลูกน้องมาทำแทน

3. We wonder if this means :
 
 • ยอดขายตกลง จากแต่ก่อนจึงอยากให้ทำอะไนที่สามารถเพิ่มยอดขายได้

4.It would be game-changing to :
 
 • ทำการจัดทำป้ายประกาศคอยโฆษณาสินค้าภายในร้าน หากมีโปรโมชั้นก็ทำป้ายใบขึ้นมา

**Comment by plaslide** [comment]
ครับ
